
package mondoincantato;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JButton;

public class SchermataIniziale extends javax.swing.JFrame {
    private Borsa b;
    private Eroe e;
    private Gestore g;
    private SceltaPersonaggio f2;
    private boolean isDemoneSelezionato = false;

    public SchermataIniziale() {
        this.setUndecorated(true);
        initComponents();
        g = new Gestore(0,false,e,b);
        configuraSchermataStoria();
    }

    private void configuraSchermataStoria() {

        Dimension dimSchermo = Toolkit.getDefaultToolkit().getScreenSize();
        int w = dimSchermo.width;
        int h = dimSchermo.height;

        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        this.setSize(w, h);

        jPanel1.setLayout(null);
        this.setContentPane(jPanel1);


        ImageIcon iconaOriginale = new ImageIcon(getClass().getResource("/mondoincantato/sfondo-mod.png"));
        Image imgScalata = iconaOriginale.getImage().getScaledInstance(w, h, Image.SCALE_SMOOTH);
        jLabelSfondo.setIcon(new ImageIcon(imgScalata));
        jLabelSfondo.setBounds(0, 0, w, h);

        // --- BOTTONE NORMALE (VERDE) ---
        int normW = (int) (w * 0.22); 
        int normH = (int) (h * 0.15);
        int normX = (int) (w * 0.70); 
        int normY = (int) (h * 0.27); 
        configuraBottoneInvisibile(difNormale, normX, normY, normW, normH);

// --- BOTTONE DEMONE (ROSSO) ---
        int demoW = (int) (w * 0.22);
        int demoH = (int) (h * 0.15);
        int demoX = (int) (w * 0.70);
        int demoY = (int) (h * 0.60); 
        configuraBottoneInvisibile(difDemone, demoX, demoY, demoW, demoH);


        
        jPanel1.add(difNormale);
        jPanel1.add(difDemone);
        jPanel1.add(jLabelSfondo);

        jPanel1.revalidate();
        jPanel1.repaint();
    }

    // Metodo per rendere i bottoni invisibili ma cliccabili 
    private void configuraBottoneInvisibile(JButton b, int x, int y, int w, int h) {
        b.setBounds(x, y, w, h);
        b.setContentAreaFilled(false);
        b.setBorderPainted(false);
        b.setText("");
        b.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        difNormale = new javax.swing.JButton();
        difDemone = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabelSfondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        difNormale.setText("NORMALE");
        difNormale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                difNormaleActionPerformed(evt);
            }
        });

        difDemone.setText("DEMONE");
        difDemone.setActionCommand("");
        difDemone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                difDemoneActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jLabelSfondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mondoincantato/sfondo-mod.png"))); // NOI18N
        jLabelSfondo.setText("jLabel4");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(646, 646, 646)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(difDemone, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(difNormale, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(80, 80, 80))
            .addGroup(layout.createSequentialGroup()
                .addGap(151, 151, 151)
                .addComponent(jLabelSfondo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(93, 93, 93))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(132, Short.MAX_VALUE)
                .addComponent(difNormale, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(difDemone, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelSfondo)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void difNormaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_difNormaleActionPerformed

        g.setMod(false);
        SceltaPersonaggio f2 = new SceltaPersonaggio(isDemoneSelezionato);
        f2.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_difNormaleActionPerformed

    private void difDemoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_difDemoneActionPerformed

        g.setMod(true);
        isDemoneSelezionato = true;
        SceltaPersonaggio f2 = new SceltaPersonaggio(isDemoneSelezionato);
        f2.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_difDemoneActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SchermataIniziale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new SchermataIniziale().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton difDemone;
    private javax.swing.JButton difNormale;
    private javax.swing.JLabel jLabelSfondo;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
