
package mondoincantato;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.SwingConstants;

public class SchermataIniziale extends javax.swing.JFrame {

    private Gestore g;
    private SceltaPersonaggio f2;
    private JLabel jLabelSfondo;

    public SchermataIniziale() {
        // 1. Togliamo i bordi di Windows
        this.setUndecorated(true); 
        
        // 2. CREIAMO I COMPONENTI (Fondamentale farlo per primo!)
        initComponents(); 
        
        // 3. Inizializziamo la tua logica
        f2 = new SceltaPersonaggio();
        g = new Gestore(false);
        
        // 4. Solo ORA che tutto esiste, configuriamo la grafica
        configuraSchermataFullscreen(); 
    }

    private void configuraSchermataFullscreen() {
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        int w = dim.width;
        int h = dim.height;

        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        this.setSize(w, h);
        
        JPanel mainPanel = (JPanel)this.getContentPane();
        mainPanel.setLayout(null);
        mainPanel.setBackground(Color.BLACK);

        // --- CONTROLLO DI SICUREZZA ---
        // Se vedi questo messaggio in console, significa che il nome nel Design è diverso!
        if (difNormale == null || difDemone == null || cambioPag == null || jLabel2 == null) {
            System.err.println("ERRORE: Uno dei componenti è NULL. Controlla i nomi nel Design!");
            return; 
        }

        // --- POSIZIONAMENTO ---
        jLabel2.setBounds((int)(w*0.25), (int)(h*0.2), (int)(w*0.5), (int)(h*0.4));
        difNormale.setBounds((int)(w*0.8), (int)(h*0.35), 180, 50);
        difDemone.setBounds((int)(w*0.8), (int)(h*0.45), 180, 50);
        cambioPag.setBounds((int)(w*0.4), (int)(h*0.8), 250, 80);

        // --- SFONDO ---
        try {
            java.net.URL imgURL = getClass().getResource("/mondoincantato/sfondo_storia_fullscreen.png");
            if (imgURL != null) {
                ImageIcon icona = new ImageIcon(imgURL);
                Image img = icona.getImage().getScaledInstance(w, h, Image.SCALE_SMOOTH);
                jLabelSfondo = new JLabel(new ImageIcon(img));
                jLabelSfondo.setBounds(0, 0, w, h);
            } else {
                System.err.println("File immagine non trovato! Controlla il nome del file .png");
            }
        } catch (Exception e) {
            System.err.println("Errore caricamento immagine: " + e.getMessage());
        }

        // --- AGGIUNTA ORDINATA ---
        mainPanel.removeAll();
        mainPanel.add(jLabel2);
        mainPanel.add(difNormale);
        mainPanel.add(difDemone);
        mainPanel.add(cambioPag);
        
        // Aggiungiamo lo sfondo solo se è stato creato correttamente
        if (jLabelSfondo != null) {
            mainPanel.add(jLabelSfondo);
        }

        mainPanel.revalidate();
        mainPanel.repaint();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        difNormale = new javax.swing.JButton();
        difDemone = new javax.swing.JButton();
        cambioPag = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 3, 24)); // NOI18N
        jLabel1.setText("STORIA DEL GIOCO:");

        jLabel2.setFont(new java.awt.Font("Source Code Pro", 1, 12)); // NOI18N
        jLabel2.setText("Ti hanno rinchiuso in una capsula con la forza, ti sei svegliato in un mondo a se stante. Sei sconvolto, ma devi prendere una scelta ");

        jLabel3.setFont(new java.awt.Font("Segoe UI Historic", 1, 18)); // NOI18N
        jLabel3.setText("SCEGLI DIFFICOLA':");

        difNormale.setText("NORMALE");
        difNormale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                difNormaleActionPerformed(evt);
            }
        });

        difDemone.setText("DEMONE");
        difDemone.setActionCommand("");
        difDemone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                difDemoneActionPerformed(evt);
            }
        });

        cambioPag.setFont(new java.awt.Font("Segoe UI Historic", 1, 24)); // NOI18N
        cambioPag.setText("NEXT");
        cambioPag.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cambioPagActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addGap(50, 50, 50))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 498, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(87, 87, 87)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(difDemone, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(difNormale, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE))
                        .addGap(80, 80, 80))))
            .addGroup(layout.createSequentialGroup()
                .addGap(311, 311, 311)
                .addComponent(cambioPag, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(difNormale, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)
                        .addComponent(difDemone, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(160, 160, 160)
                .addComponent(cambioPag, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void difNormaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_difNormaleActionPerformed
        g.setMod(false);
    }//GEN-LAST:event_difNormaleActionPerformed

    private void difDemoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_difDemoneActionPerformed
        g.setMod(true);
    }//GEN-LAST:event_difDemoneActionPerformed

    private void cambioPagActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cambioPagActionPerformed
        f2.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_cambioPagActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new SchermataIniziale().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cambioPag;
    private javax.swing.JButton difDemone;
    private javax.swing.JButton difNormale;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
