/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mondoincantato;

/**
 *
 * @author TRIVELLA.AUGUSTO
 */
public class Turno extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Turno.class.getName());

    /**
     * Creates new form Turno
     */
    private Eroe e;
    public Turno() {
        initComponents();
        e= new Eroe("nessuno",false,0,0,0,false);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ability = new javax.swing.JButton();
        mangia = new javax.swing.JButton();
        bevi = new javax.swing.JButton();
        esplora = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        valSalute = new javax.swing.JLabel();
        valFame = new javax.swing.JLabel();
        valSete = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        turno = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ability.setBackground(new java.awt.Color(255, 255, 0));
        ability.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        ability.setText("ABILITY");
        getContentPane().add(ability, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 540, -1, -1));

        mangia.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        mangia.setText("MANGIA");
        getContentPane().add(mangia, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 620, -1, -1));

        bevi.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        bevi.setText("BEVI");
        getContentPane().add(bevi, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 690, -1, -1));

        esplora.setBackground(new java.awt.Color(153, 255, 153));
        esplora.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        esplora.setText("ESLPORA");
        getContentPane().add(esplora, new org.netbeans.lib.awtextra.AbsoluteConstraints(1230, 520, -1, 250));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel2.setText("FAME-->");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 590, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel3.setText("SETE-->");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 650, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel4.setText("SALUTE-->");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 530, -1, -1));

        valSalute.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        valSalute.setText("0");
        getContentPane().add(valSalute, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 530, -1, -1));

        valFame.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        valFame.setText("0");
        getContentPane().add(valFame, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 590, -1, -1));

        valSete.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        valSete.setText("0");
        getContentPane().add(valSete, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 660, -1, -1));

        jButton1.setText("jButton1");
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, -1, -1));

        jButton2.setText("jButton2");
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 50, -1, -1));

        jButton3.setText("jButton3");
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 50, -1, -1));

        jButton5.setText("jButton5");
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 50, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("TURNO-->");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 110, -1, -1));

        turno.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        turno.setForeground(new java.awt.Color(255, 255, 255));
        turno.setText("0");
        getContentPane().add(turno, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 110, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mondoincantato/lirael.png"))); // NOI18N
        jLabel8.setText("jLabel8");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 474, 352));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mondoincantato/borraccia.png"))); // NOI18N
        jLabel9.setText("jLabel9");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 140, 454, 352));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mondoincantato/sfondo-turno.png"))); // NOI18N
        jLabel10.setText("jLabel10");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -50, 1390, 930));
        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 80, 320, 430));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Turno().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ability;
    private javax.swing.JButton bevi;
    private javax.swing.JButton esplora;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton mangia;
    private javax.swing.JLabel turno;
    private javax.swing.JLabel valFame;
    private javax.swing.JLabel valSalute;
    private javax.swing.JLabel valSete;
    // End of variables declaration//GEN-END:variables
}
